### PR TITLE
Add Kubernetes config for sandbox deployment

### PR DESCRIPTION
**Pull request by lucperkins**
This will enable people to run the sandbox version of Streamlio on Kubernetes using just two commands:

```shell
$ kubectl apply -f kubernetes/streamlio-sandbox.yaml
$ kubectl port-forward POD_ID -p 9000:9000 -p ...
```

### CODE REVIEW

**Comment by aahmed-se** [comment]
You need to add the readme modifications for this also in this commit.

**Comment by lucperkins** [comment]
@aahmed-se Done

**Comment by kramasamy** [comment]
One suggestion would be to include the kubernetes ahead of running from source files. Not many people would care about running from source files (unless they are engineers)

**Comment by kramasamy** [comment]
Also do we need wget for Kubernetes - you can directly give the URL for kubernetes as well @cckellogg and @merlimat can you explain how can we do this?

**Pull request merged**
